### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-zeta-star-wars#18]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `helpers/data/messageData.js`
**And** when they add messages it should add them to the list

## Dev Notes
**When** the page is visited 5 messages should be displayed in the text area that are clean and easy to read. As well as any new messages that are sent to the text area.

The displayed messages should show the user that they are from as well as a time stamp(#9 ) that shows when the message was sent. They should also display a button that will delete the message from the display.(#17 )

![image](https://user-images.githubusercontent.com/18632556/84098968-2ce84c80-a9ce-11ea-8ecf-d15b94961c98.png)

**Comment by nrg51098** [comment]
This ticket is finished. Now it is just to make the messages look good. But I think we have other ticket for that.
